dev/israfil/Login
FS-Code/open-appointment-backend pull request #102
Opened 2023-06-11 12:51 UTC by Israfil1993

duzelis olundu

2023-06-12 07:56 UTC, devalirzayev requested changes

2023-06-12 07:56 UTC, devalirzayev commented on app/Controllers/AuthController.php
> +                ]);
@Israfil1993 bunu irad olaraq demirem. Issue-da qeyd etmemishdim deye senin yalnishin deyil. Sadece master-e merge etmezden once duzeldersen zehmet olmasa:

Tokenin icinde email saxlamaga ehtiyac yoxdur. Bir dene `id` bes edir.

2023-06-12 07:56 UTC, devalirzayev commented on app/Controllers/AuthController.php
> +                    'token' => $token,
responseda da tokeni qaytarmayaq, cookie-de store edek

2023-06-12 11:03 UTC, Israfil1993 commented on app/Controllers/AuthController.php
> +                    'token' => $token,
duzelis olundu.

2023-06-13 13:18 UTC, devalirzayev approved these changes

2023-06-13 13:18 UTC, merged

2023-06-15 08:03 UTC, devalirzayev commented on app/Controllers/AuthController.php
> +    public function login()
@Israfil1993 function static deyil ama api.php-de static cagirmaga calishmisan

2023-06-15 08:08 UTC, devalirzayev commented on app/Controllers/AuthController.php
> +        } catch (Exception $e) {
Exception classini tapmir, cunki import elememisen.

2023-06-15 08:08 UTC, devalirzayev commented on app/Controllers/AuthController.php
> +            Response::json(['error' => $e->getMessage()]);
`Response` classinda `json` deye method yoxdur

2023-06-15 08:26 UTC, devalirzayev commented on app/Controllers/AuthController.php
> +            $user = User::getUserByEmail($email);
`email` bosh olduqda bu funksiyaya null getdiyi ucun partlayir, gerek yuxarida `::post('email', '')` ederdin ve ya null olub olmadigini yoxlayardin

2023-06-15 08:26 UTC, devalirzayev commented on app/Controllers/AuthController.php
> +                Response::json(['error' => 'Email or password is incorrect']);
burda throw exception ede bilerdin, avtomatik catchdaki kod ishe dushecekdi

2023-06-15 08:26 UTC, devalirzayev commented on app/Controllers/AuthController.php
> +                setcookie('token', $token, 0, '/');
`setcookie` funksiyasinin 3-cu argumentine 0 verdikde browser close olan kimi cookie de silinir.