Dev/ferid/model service delete
FS-Code/open-appointment-backend pull request #103
Opened 2023-06-13 20:53 UTC by feridnesibzade

2023-06-14 05:59 UTC, devalirzayev requested changes

2023-06-14 05:59 UTC, devalirzayev commented on api.php
> +Router::get('open-appointment-backend', [ HomeController::class, 'index' ] );
@feridnesibzade bu ne ucundur?

2023-06-14 08:08 UTC, feridnesibzade commented on api.php
> +Router::get('open-appointment-backend', [ HomeController::class, 'index' ] );
bu hissə önəmli deyil, sadəcə local hostumda problem oldu deyə bunu əlavə eləmişəm

2023-06-15 08:48 UTC, devalirzayev approved these changes

2023-06-15 08:48 UTC, merged