Create DateFormatHelpers file and create secondToHumanReadable function
FS-Code/open-appointment-backend pull request #17
Opened 2023-05-26 11:37 UTC by CamalPashazade

2023-05-30 07:10 UTC, devalirzayev commented
@CamalPashazade task-da qeyd olunub ki, minimum unit `minutes`, maximum ise `days` olsun. Lakin, senin methodunda minimum `seconds` ve maximum da `hours`dur. Bundan elave her zaman unit-i tekde qaytarirsan, meselen, `2hr` olacaq, amma `2hrs` olmalidir

2023-05-30 07:11 UTC, devalirzayev requested changes
@CamalPashazade task-da qeyd olunub ki, minimum unit minutes, maximum ise days olsun. Lakin, senin methodunda minimum seconds ve maximum da hoursdur. Bundan elave her zaman unit-i tekde qaytarirsan, meselen, 2hr olacaq, amma 2hrs olmalidir

2023-05-30 08:24 UTC, CamalPashazade commented
deyisdim gonderdim.baxarsiz zehmet olmasa

On Tue, May 30, 2023 at 11:11 AM Ali ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> @CamalPashazade <https://github.com/CamalPashazade> task-da qeyd olunub
> ki, minimum unit minutes, maximum ise days olsun. Lakin, senin methodunda
> minimum seconds ve maximum da hoursdur. Bundan elave her zaman unit-i tekde
> qaytarirsan, meselen, 2hr olacaq, amma 2hrs olmalidir
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FS-Code/open-appointment-backend/pull/17#pullrequestreview-1450235345>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXKO3RDQO7L4FKTP4FSEAYDXIWMRZANCNFSM6AAAAAAYQDQ3YQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-30 11:20 UTC, devalirzayev commented
@CamalPashazade 👍🏻  `days` qaldi bir dene

2023-05-31 08:10 UTC, devalirzayev commented
@CamalPashazade bu defe de, `min` ve `mins` qaldi ))

2023-05-31 12:24 UTC, devalirzayev requested changes

2023-05-31 12:24 UTC, devalirzayev commented on app/Controllers/HomeController.php
bu deyishikliklerini restore edersen

2023-06-02 06:31 UTC, devalirzayev approved these changes

2023-06-02 06:31 UTC, devalirzayev commented
Close edirem.

2023-06-02 06:31 UTC, closed without merging