Add Helper.php file
FS-Code/open-appointment-backend pull request #28
Opened 2023-05-27 20:09 UTC by sadafimanova

#12

2023-05-30 07:07 UTC, devalirzayev commented
Kod duzgun calishir ✅

2023-05-30 07:07 UTC, devalirzayev requested changes

2023-05-30 13:57 UTC, sadafimanova commented
Salam. Mən məlumat oxumuşdum ki, proyektlərdə if istifadə etməkdən qaçınmaq
lazımdı. Ona görə switch işlətmişəm. Digər dediklərinizi düzəliş edib
göndərəcəm. İndi evdə deyiləm deyə edə bilmirəm. Əlavə oıaraq mənim php
təcrübəm yoxdu. Ola bilsin ki sintaksis səhvləri edim. Java, C# üzərində
işləmişəm. Taskları aradəraraq php-ə uyğun yazmağa çalışıram

On Tue, 30 May 2023, 11:07 Ali, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In app/Helpers/Helper.php
> <https://github.com/FS-Code/open-appointment-backend/pull/28#discussion_r1209762683>
> :
>
> > @@ -0,0 +1,45 @@
> +<?php
> +
> +namespace App\Helpers;
> +
> +class Helper{
> +    public static function secondsToHumanReadable($duration) {
>
> parametrin ( int $duration ) ve method-un return type-ni (string) qeyd
> etmek lazimdir
> ------------------------------
>
> In app/Helpers/Helper.php
> <https://github.com/FS-Code/open-appointment-backend/pull/28#discussion_r1209777390>
> :
>
> > +        switch(true){
> +            case $days>0:
> +                $result.= $days. "d ";
> +                break;
> +        }
> +        switch(true){
> +            case $hours==1:
> +                $result.= $hours. "hr ";
> +                break;
> +            case $hours>1:
> +                $result.= $hours. "hrs ";
> +                break;
> +        }
> +        switch(true){
> +            case $minutes==1:
> +                $result.= $minutes. "min ";
> +                break;
> +            case $minutes>1:
> +                $result.= $minutes. "mins ";
> +                break;
> +        }
>
> ne ucun bu kodlari switch-le yazmisan anlamiram, cox maraqlidir. if-lerle
> de rahatliqla yazmaq olardi.
>
> hemcinin de unitlerin tek ve cem formalarini ternary ile yaza bilersen.
>
> example:
>
> $result .= $minutes > 1 ? "mins": "min";
>
> PHP Conditions: https://www.youtube.com/watch?v=VcQpzTPHbys
> PHP Ternary Operator:
> https://www.phptutorial.net/php-tutorial/php-ternary-operator/
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FS-Code/open-appointment-backend/pull/28#pullrequestreview-1450159497>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2X53XLI3FHTHN6TR5C4FBLXIWMDBANCNFSM6AAAAAAYRL2TXI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-31 08:36 UTC, devalirzayev commented
@sadafimanova `if` proqramlashdirmanin esas temelidir ele. Eger tapa bilseniz, melumati oxudugunuz menbenin linkini mene gondere bilersizmi? Mene de maraqli geldi.

bir de son duzelish etdiyinizi kodu run edib yoxlamisizmi? duzgun result vermir.

2023-05-31 18:28 UTC, devalirzayev commented
👍 qesheng

2023-05-31 18:28 UTC, sadafimanova commented
Duzu tam olaraq xatirlamiram. Hansisa youtube dersinde esitmisem sehv
etmiremse. Men dunen axsam kodu yeniden push etmekde cetinlik cekdim. Som
etdiyim deyisiklikler save olunmayibmis. Indi tezeden duzeltdim. Vaxtiniz
olsa yoxlayarsiniz


31 may 2023, Ç. tarixində 12:36 tarixində Ali ***@***.***>
yazdı:

> @sadafimanova <https://github.com/sadafimanova> if proqramlashdirmanin
> esas temelidir ele. Eger tapa bilseniz, melumati oxudugunuz menbenin
> linkini mene gondere bilersizmi? Mene de maraqli geldi.
>
> bir de son duzelish etdiyinizi kodu run edib yoxlamisizmi? duzgun result
> vermir.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FS-Code/open-appointment-backend/pull/28#issuecomment-1569746736>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2X53XN4GRXR6GNFWWS6OE3XI37KVANCNFSM6AAAAAAYRL2TXI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-31 18:30 UTC, closed without merging