dev/israfil/add request methods #14
FS-Code/open-appointment-backend pull request #31
Opened 2023-05-27 20:53 UTC by Israfil1993

2023-05-30 08:39 UTC, devalirzayev requested changes

2023-05-30 08:39 UTC, devalirzayev commented on app/Core/Request.php
> +        return $_GET[$key] ?? $default;
eger $_GET[$key], $_POST[$key] ve ya $_COOKIE[$key] bosh string olarsa, $default evezine onu qaytaracaq

2023-05-30 12:20 UTC, Israfil1993 commented on app/Core/Request.php
> +        return $_GET[$key] ?? $default;
duzelis etdim zehmet olmazsa baxarsiz

2023-05-30 12:22 UTC, devalirzayev commented on app/Core/Request.php
> +        return $_GET[$key] ?? $default;
Bir dene menim sehvim olub. Eslinde ne get,cookie, ne de post data sanitize olunmali deyil. Nece varsa ele de gelmelidiler. Sen birinci defe duz yazmishdin, indi niye sanitize eledin ki)))

set olunmayibsa ve ya boshdursa ( example, !isset($_GET[$key]) || trim( $_GET[$key] ) === "" ) o zaman $default qaytaraq. Bunu bir dene deyishersen kodunda zehmet olmasa.

2023-05-30 12:25 UTC, Israfil1993 commented on app/Core/Request.php
> +        return $_GET[$key] ?? $default;
istedim trimle yazim eslinde sizin kod da olan yanlisi gormusdum sadece dusundum men yanlis edirem ehtiyat etdim yenede

2023-05-31 08:37 UTC, devalirzayev commented
Approved 👍🏻 

PR close edirem, cunki artiq bashqasinin kodunu merge etmishem

2023-05-31 08:37 UTC, closed without merging