Task submit
FS-Code/open-appointment-backend pull request #39
Opened 2023-05-28 23:41 UTC by jalilverdiyev

Used a different approach

2023-05-30 08:50 UTC, devalirzayev requested changes

2023-05-30 08:50 UTC, devalirzayev commented on app/Helpers/SecondsHelper.php
> +            }
bunun evezine sadece bele yazmaq olardi axi:

```
$days = floor( $duration / 86400 );
$duration -= $days * 86400;
``` 

senin yazdigin kod while dongusu istifade edir ve dongu riyazi misala nisbetde daha az performanslidi. hem de kodun uzun olur.

2023-05-30 08:50 UTC, devalirzayev commented on app/Helpers/SecondsHelper.php
> +                    break;
```php
default:
                    $res .= $days . ( $days > 1 ? "days": "day" );
                    break;
```

umumiyyetle switch evezine if istifade etmeyin daha mentiqli olardi

2023-05-30 23:21 UTC, jalilverdiyev commented on app/Helpers/SecondsHelper.php
> +            }
burda sadece ferqli bir yanasma isletmek istemisdim ;)

2023-05-31 00:08 UTC, jalilverdiyev commented on app/Helpers/SecondsHelper.php
> +class SecondsHelper
hazırdı

2023-05-31 08:47 UTC, devalirzayev commented
👍🏻

2023-05-31 08:51 UTC, devalirzayev approved these changes

2023-05-31 08:51 UTC, closed without merging