dev/Cavidan/second-to-human
FS-Code/open-appointment-backend pull request #43
Opened 2023-05-30 11:54 UTC by Cavidan03

#12

2023-05-30 12:20 UTC, devalirzayev requested changes

2023-05-30 12:20 UTC, devalirzayev commented on app/Helpers/helper.php
> +>>>>>>> dev/Cavidan/seconds-to-human
bunlar artiq kodlardi, silersen zehmet olmasa

2023-05-30 12:20 UTC, devalirzayev commented on app/Helpers/helper.php
> + echo Helper::secondsToHumanReadable(7200);
bu kodlar da test ucun yazilmish kodlardi, test ucun yazilan kodlari esas proyekte atmayaq, bunlari da silersen z.o

2023-05-30 12:20 UTC, devalirzayev commented on app/Helpers/helper.php
> +            $result .= $minutes . 'mins';
eger gun, saat ve ya deqiqe tek olarsa, o zaman `d`,`hr`,`min` olsun, eks halda `days`, `hrs`, `mins`

2023-05-30 12:51 UTC, Cavidan03 commented
Duzeltdim

2023-05-31 12:19 UTC, devalirzayev requested changes

2023-05-31 12:19 UTC, devalirzayev commented on app/Helpers/helper.php
> +            $result .= $minutes . ($minutes%2==1 ? 'min' : 'mins');
@Cavidan03 senin yazdigin kodda eger gun, saat, deqiqe cutdurse o zaman `s` artirirsan. Ingilis dilinde eger eger say 1-den boyukdurse o zaman cem shekilcisi `s` artirilir. `%2` ile yoxlamaq duzgun deyil

2023-05-31 18:04 UTC, Cavidan03 commented on app/Helpers/helper.php
> +            $result .= $minutes . ($minutes%2==1 ? 'min' : 'mins');
@devalirzayev  Basa dusduyum qeder kodda duzelis etdim. Zehmet olmasa baxib deyerlendirerdiz.

2023-05-31 18:31 UTC, devalirzayev approved these changes
👍 super, indi düppədüzdür

2023-05-31 18:31 UTC, closed without merging