Div/rasgarov/create user
FS-Code/open-appointment-backend pull request #64
Opened 2023-05-31 16:24 UTC by rasgarov

#49

2023-06-01 13:06 UTC, devalirzayev requested changes

2023-06-01 13:06 UTC, devalirzayev commented on app/Models/User.php
> +        $existingUser = self::where('email', $email)->first();
where methodu yoxdur axi frameworkumuzde, eger ozun elave etmisense gite dushmeyib bu method

2023-06-01 13:13 UTC, rasgarov commented on app/Models/User.php
> +        $existingUser = self::where('email', $email)->first();
Hə, gitə düşməyib. Yenidən dəyişib göndərərəm

2023-06-01 13:14 UTC, devalirzayev commented on app/Models/User.php
> +        $existingUser = self::where('email', $email)->first();
hansi classa elave etmishdin? Model, DB? mence hele bu methodu elave etmeyek. Sade sql query ile yaz ele

2023-06-01 13:43 UTC, rasgarov commented on app/Models/User.php
> +        $existingUser = self::where('email', $email)->first();
Baş üstə

2023-06-01 13:45 UTC, rasgarov commented
düzəlişləri edib push etdim öz branchıma

2023-06-01 13:46 UTC, rasgarov reviewed
#49 after changes

2023-06-02 11:08 UTC, rasgarov reviewed
hash added. #49

2023-06-05 07:44 UTC, devalirzayev requested changes

2023-06-05 07:44 UTC, devalirzayev commented on app/Models/User.php
> +            $hashedPassword = password_hash($password, PASSWORD_BCRYPT);
hash prosesi bu methoda gelene qeder bash verecek, modeldeki methodun hashlamasi duzgun deyil

2023-06-05 07:46 UTC, devalirzayev requested changes

2023-06-05 07:46 UTC, devalirzayev commented on app/Models/User.php
> +        }
bu `try`-in icinde exception ata bilecek hansi funksiya var ki?

2023-06-05 09:52 UTC, rasgarov reviewed
yoxlayin zehmet olmasa

2023-06-06 16:17 UTC, devalirzayev approved these changes

2023-06-06 16:17 UTC, merged